// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACbruCp7GAdfwuvpWjsudHplY0Qwqr5S8',
    appId: '1:962562521240:web:13164688393698f74138ed',
    messagingSenderId: '962562521240',
    projectId: 'mappaterminal-7e798',
    authDomain: 'mappaterminal-7e798.firebaseapp.com',
    storageBucket: 'mappaterminal-7e798.firebasestorage.app',
    measurementId: 'G-2F0RNV0GY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBID6-sRx-mUIF1KOW9Yhg9ILhJ4-6Vkmk',
    appId: '1:962562521240:android:c3e92579bee5adc44138ed',
    messagingSenderId: '962562521240',
    projectId: 'mappaterminal-7e798',
    storageBucket: 'mappaterminal-7e798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYFqypy98QIwYHA4uRASONHGp_hHbw8zA',
    appId: '1:962562521240:ios:9aa73d697dd79bc44138ed',
    messagingSenderId: '962562521240',
    projectId: 'mappaterminal-7e798',
    storageBucket: 'mappaterminal-7e798.firebasestorage.app',
    iosBundleId: 'com.mappaterminal.app.mappaterminal1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYFqypy98QIwYHA4uRASONHGp_hHbw8zA',
    appId: '1:962562521240:ios:9aa73d697dd79bc44138ed',
    messagingSenderId: '962562521240',
    projectId: 'mappaterminal-7e798',
    storageBucket: 'mappaterminal-7e798.firebasestorage.app',
    iosBundleId: 'com.mappaterminal.app.mappaterminal1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACbruCp7GAdfwuvpWjsudHplY0Qwqr5S8',
    appId: '1:962562521240:web:2c3f2e71b4f1d9224138ed',
    messagingSenderId: '962562521240',
    projectId: 'mappaterminal-7e798',
    authDomain: 'mappaterminal-7e798.firebaseapp.com',
    storageBucket: 'mappaterminal-7e798.firebasestorage.app',
    measurementId: 'G-VC6DC9Q0H2',
  );
}
